/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IncidentsCreateResponseBody
 */
export interface IncidentsCreateResponseBody {
    /**
     * Unique identifier for the incident
     * @type {string}
     * @memberof IncidentsCreateResponseBody
     */
    id: string;
    /**
     * Name of the incident
     * @type {string}
     * @memberof IncidentsCreateResponseBody
     */
    name: string;
}

export function IncidentsCreateResponseBodyFromJSON(json: any): IncidentsCreateResponseBody {
    return IncidentsCreateResponseBodyFromJSONTyped(json, false);
}

export function IncidentsCreateResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentsCreateResponseBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function IncidentsCreateResponseBodyToJSON(value?: IncidentsCreateResponseBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}


